### ISSUE TITLE
ZeroDivisionError: float division by zero on *black*

### ISSUE THREAD

**Issue by xuchen** [benknight/hue-python-rgb-converter#1]
``` Python
from rgb_cie import Converter
converter = Converter()
converter.rgbToCIE1931(0, 0, 0)
```

Then there is:

```
ZeroDivisionError: float division by zero
```

I thought I would trick the function to give it a color closest to black: (1,1,1), however, the function returns the same value for white: (255, 255, 255):

``` Python
In [1]: converter.rgbToCIE1931(1, 1, 1)
Out[1]: [0.33618074375880236, 0.3603696362840742]

In [2]: converter.rgbToCIE1931(255, 255, 255)
Out[2]: [0.33618074375880236, 0.3603696362840742]
```

So basically there are two issues:
- ZeroDivisionError, easy to fix
- `getClosestPointToPoint()` returns identical values for "black" and "white"

Any ideas on how to fix the second one? I couldn't find any point near "black" from the hue color map:

http://www.developers.meethue.com/documentation/core-concepts

Maybe turn it off? ;-)

**Comment by benknight** [comment]
I fixed the divide by zero error by adding a simple conditional.

Regarding your second issue, I don't think this is actually a bug.  An XY value really just represents a hue, so if you wanted "close to black" you'd take the XY value for white and set brightness as low as possible.

**Comment by xuchen** [comment]
That's right! Thanks for fixing it!
