### ISSUE TITLE
New Hue products and their expanded color gamuts

### ISSUE THREAD

**Issue by kershner** [benknight/hue-python-rgb-converter#2]
Hi Ben,

First of all - great work on this converter script.  I see it used all over the place in various Hue apps including [mine](https://github.com/kershner/screenBloom/), so I think it's safe to say your code here facilitates a lot of third party Hue development and I'm grateful to you for that.

I've had a couple of users suggest that my app (which takes an RGB value and converts to Hue CIE via your module) is potentially producing unexpected colors on the newer generation Hue hardware.  I know the new stuff has potentially different color gamuts, but I have no way to verify this in practice as I'm still on a bunch of Gen 1 stuff.

So I just wanted to quickly ask you if you can envision this kind of thing being a problem for your module, or if my user is possibly missing something or misunderstanding the color that was produced.

Thanks!

**Comment by benknight** [comment]
Hey @kershner there's a good chance the conversion code here doesn't apply well to the newer hue lights which have different gamuts.

When I have some time I'll dig into this more and see if there's any updated code provided by Philips.

This looks relevant: http://www.developers.meethue.com/documentation/hue-xy-values

**Comment by benknight** [comment]
As I recall there used to be a README somewhere buried in the Philips iOS SDK repo but I don't see it anymore.  They used to have a step-by-step implementation guide for converting from RGB to XY color.  That must have been back when there was only one gamut to consider.  Now it appears there are 3.

**Comment by benknight** [comment]
I have proposed a fix in PR #3.  Once I have a chance to test and verify it's working correctly I'll merge it.

**Comment by kershner** [comment]
Awesome!  I really appreciate you taking the time to investigate this.

**Comment by kershner** [comment]
Haven't had the time to implement the new changes into my own application but the issue has been addressed very nicely with your recent updates.  If there are any issues with the new implementation I will be sure to raise them.  Thanks for the quick resolution.
